plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	maven {
		name = 'ParchmentMC'
		url 'https://maven.parchmentmc.org'
	}

	exclusiveContent {
		forRepository {
			maven {
				name = "TerraformersMC"
				url "https://maven.terraformersmc.com/"
			}
		}
		filter {
			includeGroup "dev.emi"
			includeGroup "com.terraformersmc"
		}
	}

	maven {
		name = "Modrinth"
		url "https://api.modrinth.com/maven"
	}
	maven {
		name = "Curseforge"
		url "https://cursemaven.com"
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
	}
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// Sol
	modImplementation "maven.modrinth:sollib:${sollib_version}"

	// EMI
	modImplementation "maven.modrinth:emi:${emi_version}"
	//modLocalRuntime "maven.modrinth:reliable-emi:4.6.3-1.21.1-fabric"
	//modLocalRuntime "net.fabricmc:fabric-language-kotlin:1.13.9+kotlin.2.3.10"
	//modLocalRuntime "maven.modrinth:yacl:3.8.2+1.21.1-fabric"

	// ModMenu
	modLocalRuntime "com.terraformersmc:modmenu:11.0.4"

/*
	// So many staff type dependencies ._.
	// Botania
	modCompileOnly "vazkii.botania:Botania:1.20.1-453-FABRIC"
	// Feathers
	modCompileOnly "curse.maven:feathers-699933:4814309"
	// Electroblob
	modCompileOnly "maven.modrinth:electroblobs-wizardry-redux:0.8.5.1-fabric"
	// Affinity
	modCompileOnly "maven.modrinth:affinity:0.1.8+1.20"
	modCompileOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.2.3"
	modCompileOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.2.3"
	modCompileOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-chunk:5.2.3"
	modCompileOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-item:5.2.3"
	// Spell Engine
	modCompileOnly "maven.modrinth:spell-engine:0.15.12+1.20.1"
	modCompileOnly "maven.modrinth:spell-power:0.12.0+1.20.1"
	modCompileOnly "curse.maven:rpgmana-1021902:6204209"
	// Origins
	modCompileOnly "com.github.apace100:origins-fabric:v1.10.1"
	// Goety
	modCompileOnly "maven.modrinth:goety-fabric:0.3.5-forge2.5.54.5+mc1.20.1"
	// Caverns & Chasms
	modCompileOnly "maven.modrinth:caverns-and-chasms:2.1.3"
	// RebornCore (Fabric Energy)
	modCompileOnly "teamreborn:energy:4.0.0"
	modCompileOnly "maven.modrinth:reborncore:sWpmIISP"*/
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}
