plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	maven {
		name = 'ParchmentMC'
		url 'https://maven.parchmentmc.org'
	}

	maven {
		name = "JitpackASM"
		url 'https://jitpack.io'
	}

	maven {
		name = "TerraformersMC"
		url "https://maven.terraformersmc.com/"
	}

	// Botania needs these
	maven {
		name = "BlameJared"
		url 'https://maven.blamejared.com'
	}
	maven {
		name = "JamiesWhiteShirt"
		url "https://maven.jamieswhiteshirt.com/libs-release"
	}
	maven {
		name = "Ladysnake Libs"
		url 'https://maven.ladysnake.org/releases'
	}

	maven {
		name = "Modrinth"
		url "https://api.modrinth.com/maven"
	}
	maven {
		name = "Curseforge"
		url "https://cursemaven.com"
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered {
		officialMojangMappings()
		parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
	}
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// Sol
	modImplementation "curse.maven:sollib-1573497:8242786"

	// Fabric ASM
	modImplementation "com.github.Chocohead:Fabric-ASM:v${project.fabric_asm_version}"
	include "com.github.Chocohead:Fabric-ASM:v${project.fabric_asm_version}"

	// EMI
	modCompileOnly "dev.emi:emi-fabric:${emi_version}:api"
	modLocalRuntime "dev.emi:emi-fabric:${emi_version}"
	modLocalRuntime "maven.modrinth:emi-plus-backport:tbcT7hXz"
	modLocalRuntime "net.fabricmc:fabric-language-kotlin:1.13.9+kotlin.2.3.10"
	modLocalRuntime "maven.modrinth:forge-config-api-port:v8.0.3-1.20.1-Fabric"

	// ModMenu
	modLocalRuntime "com.terraformersmc:modmenu:7.2.2"

	// Botania
	modCompileOnly "vazkii.botania:Botania:1.20.1-453-FABRIC"
	// ISS
	modCompileOnly "curse.maven:irons-spells-n-spellbooks-855414:8237094"
	// Feathers
	modCompileOnly "curse.maven:feathers-699933:4814309"
	// Electroblob
	// https://electroblobs-redux-wiki.pages.dev/developer/adding_cast_items.html
	modCompileOnly "maven.modrinth:electroblobs-wizardry-redux:0.8.5.1-fabric"
	// SpellsNShields - Requires forge api stuff and I can't import it
	//modCompileOnly "curse.maven:spells-shields-582301:5047887"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
